### ISSUE TITLE
Last few things that need be added

### ISSUE THREAD

**Issue by thepotatoarmyhd** [NavidK0/Carbon-2#13]
Bows don't work in survival.
all Items appear as stone when dropped.
When you eat Chorus Fruit you should be randomly reported near by.
When you break a Beetroot Seed when its grown you should get 0-3 Beetroot seeds and 1 Beetroot, (You just get 1 normal seed when u break it).
New Mob doesn't spawn.
New arrows don't work.
The new end doesn't generate .

------------------------ Not so in-portent stuff (for me) ------------------------ 

TheEnd world generation is not required, (I Have preloaded it on a 1.9 server and put it in my carbon server, works fine) 

New arrows don't work, (Doesn't really matter because u can only get them from creative)

---

That's really everything, I'm sure you could get all of this stuff added in a few days?

**Comment by PatoTheBest** [comment]
Did you compile the latest version? Should fix the datawatcher conflitcts

**Comment by thepotatoarmyhd** [comment]
Hi, PatoTheBest 

I'm using the latest dev build of carbon (#70)

**Comment by PatoTheBest** [comment]
Download the stc and complile it, the datawatcher is fixed on the code

**Comment by thepotatoarmyhd** [comment]
Well i don't really know how to compile it without errors :/

When will it be added in the dev builds?

**Comment by thepotatoarmyhd** [comment]
Okay stone bug was fixed, Now the only thing left to be fixed really for me is the  Beetroot Seed and that should do the trick for a while ;)
