### ISSUE TITLE
Implementing 1.8 Players  - 1.9 Players Into the same "Hub" server 

### ISSUE THREAD

**Issue by unicxa** [NavidK0/Carbon-2#14]
I am having  a slight issue that carbon didnt have, Now since Carbon-2 is out i cannot have player on 1.8 and 1.9 client on the same Hub together with carbon installed on both spigot servers linked together via Bungee, for now only 1.9 clients can connect,  is there a fix around this?

If i need to specify more please feel free to ask,
                          Thanks Again,

**Comment by Shevchik** [comment]
We are not providing support for 1.8 right now.

**Comment by thepotatoarmyhd** [comment]
What do you mean only 1.9 client can connect? How do u get bungee to accept 1.9 players?

**Comment by PatoTheBest** [comment]
The bungee part hasnt been wtitten yet

**Comment by FALL1N1** [comment]
Any updates on this?

**Comment by Shevchik** [comment]
No, we are on hold until next snapshot. Mojang started to change the way how all things work, not just adding thing, so we probably won't continue until they finish changing things.

**Comment by KyrneDev** [comment]
If I am not using bungee cord will my server accept 1.8 and 1.9 clients? Or will it only accept 1.9?

**Comment by FALL1N1** [comment]
it will accept both.

**Comment by FALL1N1** [comment]
@issyrocks12  Figured it out, use this bungeecord: 
https://github.com/SpigotMC/BungeeCord/tree/snapshot

Just revert it's protocol id to the one carbon uses and you should be fine. :)
