### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by JustBru00** [NavidK0/Carbon-2#23]
I feel like a noob :D but, how do I install this on my server.

Thanks,
JustBru00

**Comment by PatoTheBest** [comment]
The newest snapshots aren't supported since mojang changed how entities are rendered, so we have to recode some packets. All of the team, including me, have been very busy with school/college/work and haven't had te opportunity to work on this project.

**Comment by JustBru00** [comment]
Okay thanks, if you could tell me when it is ready to use. I can't wait to use it on my SMP server.
